### ISSUE TITLE
Migration-Framework does not send response if the YAML message has a wrong format

### ISSUE THREAD

**Issue by spickartz** [RWTH-OS/migration-framework#27]
It would be nice if the Migration-Framework indicates if the YAML that has been sent does not match the definition, e.g., if I send

```
task: start vm
list:
  - vm-name: fast-vm-base
    vcpus: 8
    memory: 1048576
...
```

The Migration-Framework complains by showing

```
Exception: Error loading YAML-node: Node is not valid.
```

But the according MQTT channel (`fast/migfra/<hostname>/result`) stays silent.
