### ISSUE TITLE
Add repin option to swap migration

### ISSUE THREAD

**Issue by spickartz** [RWTH-OS/migration-framework#58]
It would be valuable to have the option of repining VMs when using the swap migration. I would suggest the following message format:

```
---
task: migrate vm
vm-name: <src vm>
vcpu-map: <map for src vm>
destination: <dest host>
time-measurement: <true/false>
parameter:
  migration-type: <warm/live>
  rdma-migration: <true/false>
  swap-with: 
    vm-name: <swap vm>
    vcpu-map: <map for swap vm> 
...
```

Any suggestions for improvements?
