### ISSUE TITLE
Pscom suspend/resume for swap migration

### ISSUE THREAD

**Issue by spickartz** [RWTH-OS/migration-framework#60]
Currently, the swap migration feature only suspends/resume processes on the "source" VM but does not consider any processes on the swap-VM. This should be changed such that the `Pscom_handler` suspends/resumes all affected processes.

**Comment by spickartz** [comment]
I would suggest an interface in accordance with #58:
```
---
task: migrate vm
vm-name: <src vm>
vcpu-map: <map for src vm>
destination: <dest host>
time-measurement: <true/false>
parameter:
  migration-type: <warm/live>
  rdma-migration: <true/false>
  swap-with: 
    vm-name: <swap vm>
    pscom-hook-procs: <procs on swap vm> 
...
```
